# Generated by Django 5.2 on 2025-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='transferencia', max_length=50),
        ),
    ]
